steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/football-data-backend', '.']
    secretEnv: ['DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_NAME', 'DB_PORT']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/football-data-backend']

  # Deploy to Cloud Run in the `us-central1` region
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'football-data-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/football-data-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--concurrency'
      - '10'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--add-cloudsql-instances'
      - 'upbeat-voice-433617-n9:us-central1:mi-cloudsql-instance'

availableSecrets:
  secretManager:
    - versionName: projects/upbeat-voice-433617-n9/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/upbeat-voice-433617-n9/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/upbeat-voice-433617-n9/secrets/DB_HOST/versions/latest
      env: 'DB_HOST'
    - versionName: projects/upbeat-voice-433617-n9/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'
    - versionName: projects/upbeat-voice-433617-n9/secrets/DB_PORT/versions/latest
      env: 'DB_PORT'

options:
  machineType: 'E2_HIGHCPU_8'
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
